### ISSUE TITLE
Question about parameter "res"

### ISSUE THREAD

**Issue by 05RMX5O** [Eromera/erfnet#1]
Hi,
    I have tried the code with different relative resolutions. I found that when res = 0.5, the IOUs are as follows. 
 + average row correct: 82.642014403092%
 + average rowUcol correct (VOC measure): 71.458449646046%
    But when I tried with res = 1 and res = 0.25, IOUs are different to a large extent:

**res = 0.25:**
 + average row correct: 73.630133584926%
 + average rowUcol correct (VOC measure): 59.288728394006%

**res = 1.0**
+ average row correct: 66.633851277201%
+ average rowUcol correct (VOC measure): 52.937617231356%

    Why there are such a large different in these results?

thanks.

**Comment by Eromera** [comment]
Hi!
I'm gonna need some more details:
In which code are you getting these values, in evaluation of an already trained model or while training your own model? 
Where are you changing this res value?

Thanks!

**Comment by 05RMX5O** [comment]
Hi,
I get these values from  eval_cityscapes_confussionMatrix.lua using the following script(with -r 0.25 or 1):
 th eval_cityscapes_confussionMatrix.lua --mode val  --dataPath /my/cityscapes/ -m erfnet_pretrained -r 0.25 -o confussionMatrix.txt
I havent trained my own model, an already trained model is used.

**Comment by Eromera** [comment]
Hi,

Since that model has been specifically fine-tuned with r=0.5, the low values on other resolutions seem reasonable. For other resolutions, it would be best to fine-tune the model on those specific resolutions. Also, if you need a model that is invariant to scale, the best option is to train by performing random scaling of each batch between 0.25 and 1. This would yield a slightly lower value than on each specific resolution (~70/71%) but stable on those three ratios.
Hope this helps!

**Comment by 05RMX5O** [comment]
I see. Thanks!
