### ISSUE TITLE
Processing speed on CPU

### ISSUE THREAD

**Issue by mkstmyk** [Eromera/erfnet#10]
I'm looking for a faster semantic segmentation architecture and comparing ENet and ERFNet these days.
In my understanding, ERFNet should run around two times faster than ENet according to the paper.
However, it runs about 7 to 8 times slower on my environment, about 2000ms for ENet, 14500ms for ERFNet to process a Cityscape data set image.
I know ERFNet itself is not likely to be the main cause for this issue because I'm loading the model from OpenCV for Unity w/o GPU, but I appreciate if you give me any hits to run ERFNet to the fullest.
Are the model (erfnet_scratch.net) and ERFNet is optimized for GPU and can't run fully only w/ CPU in theory?
Thank you in advance.

**Comment by Eromera** [comment]
Hi, ENet should in fact be twice as fast as ERFNet since the point of ERFNet is to have higher accuracy while not sacrificing much efficiency in order to have a good trade-off. I haven't tested in CPU but it is possible that it is much slower in CPU since the efficiency of ERFNet is mostly obtained from the factorized 1D convolutions so it is possible that these are ran efficiently by CUDA but not so efficiently by the CPU. However this is something that I haven't tested so it is only a theory...

**Comment by mkstmyk** [comment]
Thank you for your very quick and precise response, and sorry for misunderstanding the advantage of ERFNet.
It's great to know where its efficiency comes from.
Thank you again for your very impressive work.
